bfhl:
  name: "John Doe"        # <-- change to your name
  regNo: "REG12347"       # <-- change to your reg no.
  email: "john@example.com" # <-- change to your email
  baseUrl: "https://bfhldevapigw.healthrx.co.in"
  generatePath: "/hiring/generateWebhook/JAVA"
  # If API ever omits 'webhook' (rare), we'll fall back to this:
  fallbackSubmitPath: "/hiring/testWebhook/JAVA"

logging:
  level:
    root: INFO
    com.example.bfhl: DEBUG